# .circleci/config.yml
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "12.1"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Fetch Cocoapods Specs
          comand: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install Cocoapods
          command: pod install --verbose
          
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iphone 12
            SCAN_SCHEME: LargeProject
            
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
          
  workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test
